default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5e5
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 2000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

MotorCrawlerBrain:
    normalize: true
    time_horizon: 1000
    batch_size: 2048
    buffer_size: 20480
    gamma: 0.995
    num_layers: 3
    hidden_units: 256

VisionCrawlerBrain:
    time_horizon: 1000
    batch_size: 2048
    buffer_size: 20480
    hidden_units: 256
    num_layers: 3
